add index, dockerfile and github flow push docker image to ghcr
privacybydesign/irma-demos pull request #12
Opened 2024-11-07 15:30 UTC by saravahdatipour

2024-11-08 10:36 UTC, DibranMulder requested changes
Could you please alter the README.MD like @ivard did in https://github.com/privacybydesign/irma-demos/pull/8 
Which commands do you use to startup this demo?

Also very nice that you added a status check which docker build. In the future we could add tests if needed.

2024-11-12 09:59 UTC, DibranMulder approved these changes, later dismissed

2024-11-13 09:32 UTC, w-ensink approved these changes

2024-11-13 09:38 UTC, kamphuisem approved these changes

2024-11-13 09:38 UTC, merged